
[functions.google-reviews]
enabled = true
verify_jwt = false
import_map = "./functions/google-reviews/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-reviews/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-reviews/*.html" ]

[functions.fetch-doctoralia-opinions]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-doctoralia-opinions/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-doctoralia-opinions/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-doctoralia-opinions/*.html" ]
